---
- name: Nginx Install
  hosts: clones
  become: true

  tasks:
    - name: Install NGINX
      apt:
        name:
          - nginx
          - nginx-common
          - nginx-full
        state: present
